{{ if eq .Values.encryption.enabled true }}  
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "app.name" . }}-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
{{ end }}    